---
- name: install gui packages
  become: yes
  with_items: "{{ gui_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: configure slim
  become: yes
  template:
    src: slim.conf.j2
    dest: /etc/slim.conf

- name: configure trackpoint in X
  become: yes
  template:
    src: 20-thinkpad.conf.j2
    dest: /usr/share/X11/xorg.conf.d/20-thinkpad.conf
    owner: root
    group: root

    #- name: install gui testing packages
    #  become: yes
    #  with_items: "{{ gui_testing_packages }}"
    #  apt:
    #    pkg: "{{ item.name }}"
    #    default_release: "stretch"
    #    state: latest
