---
- name: Desktop provisioning
  hosts: all
  pre_tasks:
    - include: roles/common/pre_tasks/main.yml
  roles:
    - common
    - audio
    - gui
    - network
    - photo
    - user
    - utils
    - video
    - web
