---
user_directories:
  - path: Files
  - path: Music
  - path: repos

user_repositories:
  - repo: "https://github.com/krlex/dotfiles"
    dest: "dotfiles"

user_config:
  - name: ".gnupg"
  - name: ".netrc"
  - name: ".ssh"
  - name: "MusE"
