---
- name: ensure user exists
  become: yes
  user:
    name: "{{ user }}"
    shell: /usr/bin/fish
    groups: cdrom,floppy,sudo,audio,dip,video,plugdev,netdev

- name: clone user repositories
  become: yes
  become_user: "{{ user }}"
  with_items: "{{ user_repositories }}"
  git:
    repo: "{{ item.repo }}"
    dest: "~{{ user }}/{{ item.dest }}"

- name: init configuration of programs
  become: yes
  become_user: "{{ user }}"
  command: "~{{ user }}/.dotfiles/init.sh"
  args:
    creates: "~{{ user }}/.vim"

- name: setup regular mail checking
  become: yes
  become_user: "{{ user }}"
  cron:
    name: "mail checking"
    job: "~/bin/cron.sh"
    minute: "*"
    user: "{{ user }}"
