---
- name: install apt-transport-https
  become: yes
  apt:
    pkg: apt-transport-https
    state: latest

- name: remove default sources
  become: yes
  file:
    path: /etc/apt/sources.list
    state: absent

- name: configure debian sources
  become: yes
  template:
    src: "roles/common/templates/debian.list.j2"
    dest: "/etc/apt/sources.list.d/debian.list"
    owner: root
    group: root

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
